version: "3.1"

services:
  db:
    image: postgres
    restart: always
    env_file: ./.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: blog